#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""A store's identity must be one a COPY cannot carry.

MEASURED 2026-08-10 on two live PostgreSQL clusters, which is why this module
exists rather than a stricter comparison of ``store_uuid``:

    127.0.0.1:5432          127.0.0.1:5442
    store_uuid   1d55dd6e-…-a78835ab988f    1d55dd6e-…-a78835ab988f   IDENTICAL
    schema_version           9                        9              identical
    created_at        2026-07-16T19:24:40Z    2026-07-16T19:24:40Z    identical
    ------------------------------------------------------------------------
    tasks                 3602                     3422              DIVERGED
    max(last_activity) 2026-08-10T01:16Z      2026-08-07T05:09Z       DIVERGED

Every identity field a client could read was byte-identical while the DATA was
180 cards and three days apart. ``store_uuid`` is a ROW in ``schema_meta``, and
a dump/restore into a second cluster carries rows — which is precisely how
those two came to share one. An identity that survives being copied cannot
answer "am I connected to the store I think I am".

``system_identifier`` is generated by ``initdb`` for the CLUSTER and appears in
no dump, so a restore cannot carry it. The two clusters above differ on it, and
that difference is the question this card was asking.

WHAT THESE TESTS PIN, and one thing they deliberately do not: they pin the
PROBE's contract — that a real server answers KNOWN, that SQLite answers
UNKNOWN with a stated reason rather than an invented value, and that the type
itself refuses the shapes that would let a caller mistake absence for a value.
They do NOT claim any guard consumes it yet; the guard is the next step and
owns its own tests, because having the instrument is exactly what makes the
missing guard LOOK done.
"""

from __future__ import annotations

import os

import pytest

from scitex_cards._db import connect
from scitex_cards._store_instance import (
    Certainty,
    IdentityVerdict,
    StoreInstance,
    check_store_identity,
    store_instance,
)
from scitex_cards._store_url import BACKEND_POSTGRES, BACKEND_SQLITE

#: Same contract as ``test__sql_null_safe``: UNDECLARED skips, DECLARED-but-
#: broken fails. A Postgres-only test that skips is indistinguishable from a
#: passing one in a green summary, so declaring a server removes the excuse.
_ENV_PG_DSN = "SCITEX_CARDS_TEST_PG_DSN"


@pytest.fixture
def pg_conn():
    """A live Postgres connection, or a skip when none is declared."""
    dsn = os.environ.get(_ENV_PG_DSN)
    if not dsn:
        pytest.skip(f"{_ENV_PG_DSN} is not set — no Postgres declared")
    conn = connect(dsn)
    try:
        yield conn
    finally:
        conn.close()


@pytest.fixture
def sqlite_conn(tmp_path):
    """A real SQLite store on disk. No mocks (STX-NM)."""
    conn = connect(str(tmp_path / "cards.db"))
    try:
        yield conn
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# The probe
# ---------------------------------------------------------------------------
def test_a_postgres_connection_knows_its_instance(pg_conn):
    """A real server answers KNOWN — the probe is not merely well-typed."""
    # Arrange
    conn = pg_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.certainty is Certainty.KNOWN


def test_a_postgres_instance_id_is_the_clusters_own_identifier(pg_conn):
    """The value is the cluster's, read from the server, not synthesised.

    Reads the control row through ``_sole_value`` rather than ``row[0]``. The
    first draft of this test used the index and raised ``KeyError: 0`` against
    a real server — psycopg's ``dict_row`` yields a real dict, which accepts
    only the NAME. That is the fourth instance of the bug ``_sole_value``'s own
    docstring calls "a pattern rather than three accidents", found by writing a
    test for something else, which is the argument for the helper existing.
    """
    # Arrange
    from scitex_cards._schema_probe import _sole_value

    expected = str(
        _sole_value(
            pg_conn.execute(
                "select system_identifier::text from pg_control_system()"
            ).fetchone()
        )
    )
    # Act
    instance = store_instance(pg_conn)
    # Assert
    assert instance.instance_id == expected


def test_a_sqlite_connection_cannot_know_its_instance(sqlite_conn):
    """UNKNOWN is the honest answer for a file, not a gap to paper over."""
    # Arrange
    conn = sqlite_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.certainty is Certainty.UNKNOWN


def test_a_sqlite_answer_carries_no_invented_identity(sqlite_conn):
    """A stable-but-invented value (a path hash, say) would be WORSE than none.

    It would look like an instance identity and would FOLLOW A COPY — the exact
    failure this module exists to detect, reintroduced by the fix for it.
    """
    # Arrange
    conn = sqlite_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.instance_id is None


def test_a_sqlite_answer_says_why_it_cannot_tell(sqlite_conn):
    """"Cannot tell" without a reason is indistinguishable from a broken probe."""
    # Arrange
    conn = sqlite_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert "sqlite" in (instance.reason or "")


def test_the_backend_comes_from_the_live_connection(sqlite_conn):
    """Read from what is actually open, never from a caller's belief.

    Same rule as ``_inbox_shape.shape_for``; on this module being wrong about
    the backend means answering a question about the wrong instance.
    """
    # Arrange
    conn = sqlite_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.backend == BACKEND_SQLITE


# ---------------------------------------------------------------------------
# The type refuses the shapes that would let absence pass for a value.
#
# These run the VALIDATOR, which is the only thing standing between a caller
# and a comparison that cannot fail. Each varies ONE condition: nothing else
# about the construction is wrong, so a test passing here cannot be passing
# for another reason. (A guard exercised only through cases that also fail for
# a second reason is untested — scitex-db measured exactly that on their own
# preflight guard the same night this was written: they deleted it and 21
# tests stayed green.)
# ---------------------------------------------------------------------------
def _refusal_message(**kwargs) -> str:
    """The text the validator refuses ``kwargs`` with.

    Mirrors ``test__store_verify._verify_error_message``: the raise is the
    expectation here, so a test built on this helper spends its one assertion
    on WHICH refusal it got — a bare ``pytest.raises(ValueError)`` would pass
    on any of the four and prove none of them.
    """
    with pytest.raises(ValueError) as excinfo:
        StoreInstance(**kwargs)
    return str(excinfo.value)


def test_a_known_identity_must_carry_the_value_it_claims_to_know():
    """KNOWN with no id is a claim with nothing behind it."""
    # Arrange
    claimed = {"backend": BACKEND_POSTGRES, "certainty": Certainty.KNOWN}
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "must carry the value" in message


def test_an_unknown_identity_must_not_carry_a_value():
    """Otherwise two UNKNOWNs compare EQUAL on a shared placeholder.

    That is the collapse this module exists to prevent, reintroduced at the
    type level — the most expensive place to hide it, because every caller
    would then be correct by inspection and wrong in fact.
    """
    # Arrange — a stated reason, so ONLY the id is wrong here
    claimed = {
        "backend": BACKEND_SQLITE,
        "certainty": Certainty.UNKNOWN,
        "instance_id": "placeholder",
        "reason": "sqlite: cannot tell",
    }
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "two unknowns can never compare equal" in message


def test_an_unknown_identity_must_say_why():
    """A caller cannot tell a missing capability from a broken connection."""
    # Arrange
    claimed = {"backend": BACKEND_SQLITE, "certainty": Certainty.UNKNOWN}
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "must say why" in message


def test_a_known_identity_carries_no_reason():
    """A reason explains an UNKNOWN; on a KNOWN it is a contradiction."""
    # Arrange
    claimed = {
        "backend": BACKEND_POSTGRES,
        "certainty": Certainty.KNOWN,
        "instance_id": "7668165447904178049",
        "reason": "this should not be here",
    }
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "reason explains an UNKNOWN" in message


# ---------------------------------------------------------------------------
# The guard. Only MATCHES proceeds.
#
# THE ISOLATING CASE is `test_a_pinned_identity_that_differs_refuses`: expected
# is SET, certainty is KNOWN, the connection is live and the schema current —
# everything valid, ONE condition varying. Delete the mismatch branch and that
# test goes red while every other test here stays green, which is what makes it
# a gate rather than a formality.
#
# It is written that way on purpose. A guard exercised only through cases that
# ALSO fail for a second reason is untested — scitex-db measured exactly that
# on their own preflight guard the night this was written: they deleted it and
# 21 tests stayed green, because every case asserting failure also carried a
# failing finding.
# ---------------------------------------------------------------------------
def test_a_pinned_identity_that_matches_proceeds(pg_conn):
    """The positive control: without it, a guard that refuses everything passes.

    BOTH HALVES ARE PINNED HERE, and that is a DELIBERATE CHANGE made
    2026-08-19 rather than a repair to a broken test. Until then this passed
    the instance alone and expected ``may_proceed is True``; it now supplies a
    uuid pair as well, because an instance-only pin answers ``CANNOT_TELL``
    under the corrected contract.

    WHY THE CONTRACT CHANGED: the instance identifies the SERVER. A database
    frozen and restored onto that same server keeps its ``system_identifier``
    and gets a NEW ``store_uuid``, so an instance-only pin passes exactly the
    2026-08-09 frozen-store incident the pin exists to catch. See
    ``_store_identity_decision.decide_identity`` for all nine rows and
    ``test__identity_decision_both_halves.py`` for the per-half mutation table.

    THE PURPOSE OF THIS TEST IS UNCHANGED and is why it was updated rather than
    deleted: it is the one case asserting a PASS, so it is what stops a guard
    that refuses everything from looking correct.
    """
    # Arrange
    pinned = store_instance(pg_conn).instance_id
    pinned_uuid = "1d55dd6e-3d2a-4c24-a429-a78835ab988f"
    # Act
    check = check_store_identity(
        pg_conn,
        pinned,
        observed_uuid=pinned_uuid,
        expected_uuid=pinned_uuid,
    )
    # Assert
    assert check.may_proceed is True


def test_a_pinned_identity_that_differs_refuses(pg_conn):
    """ISOLATING: everything valid, only the VALUE differs.

    The wrong value here stands in for the measured case — two live clusters
    carrying store_uuid 1d55dd6e-…-a78835ab988f with 180 cards and three days
    between them. One cluster is enough to pin the behaviour; the second is
    what proved it was needed.
    """
    # Arrange
    not_this_cluster = "7671108644284358700"
    # Act
    check = check_store_identity(pg_conn, not_this_cluster)
    # Assert
    assert check.verdict is IdentityVerdict.DIFFERS


def test_a_differing_identity_names_both_sides(pg_conn):
    """A refusal a reader cannot check is a refusal they must take on faith."""
    # Arrange
    not_this_cluster = "7671108644284358700"
    # Act
    check = check_store_identity(pg_conn, not_this_cluster)
    # Assert
    assert not_this_cluster in (check.reason or "")


def test_nothing_pinned_cannot_tell(sqlite_conn):
    """An unpinned client is the one that reads a stale replica confidently."""
    # Arrange
    conn = sqlite_conn
    # Act
    check = check_store_identity(conn, None)
    # Assert
    assert check.verdict is IdentityVerdict.CANNOT_TELL


def test_nothing_pinned_does_not_proceed(sqlite_conn):
    """CANNOT_TELL refuses. Collapsing it into a pass is the defect itself.

    Separate from the verdict assertion above because the verdict and the
    PERMISSION are different claims: a later refactor could keep the verdict
    correct and let `may_proceed` fall through.
    """
    # Arrange
    conn = sqlite_conn
    # Act
    check = check_store_identity(conn, None)
    # Assert
    assert check.may_proceed is False


def test_a_store_that_cannot_report_an_identity_cannot_tell(sqlite_conn):
    """Pinned, but the store cannot answer — still a refusal, not a pass."""
    # Arrange
    conn = sqlite_conn
    # Act
    check = check_store_identity(conn, "7668165447904178049")
    # Assert
    assert check.may_proceed is False


def test_the_two_refusals_do_not_share_a_message(sqlite_conn):
    """"Wrong store" and "cannot tell which store" need different actions.

    The reason string is the only part a human acts on, so the two refusals
    staying distinguishable is the feature, not the wording.
    """
    # Arrange
    conn = sqlite_conn
    # Act
    unpinned = check_store_identity(conn, None).reason
    unanswerable = check_store_identity(conn, "7668165447904178049").reason
    # Assert
    assert unpinned != unanswerable


# EOF
