#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""A store's identity must be one a COPY cannot carry.

MEASURED 2026-08-10 on two live PostgreSQL clusters, which is why this module
exists rather than a stricter comparison of ``store_uuid``:

    127.0.0.1:5432          127.0.0.1:5442
    store_uuid   1d55dd6e-…-a78835ab988f    1d55dd6e-…-a78835ab988f   IDENTICAL
    schema_version           9                        9              identical
    created_at        2026-07-16T19:24:40Z    2026-07-16T19:24:40Z    identical
    ------------------------------------------------------------------------
    tasks                 3602                     3422              DIVERGED
    max(last_activity) 2026-08-10T01:16Z      2026-08-07T05:09Z       DIVERGED

Every identity field a client could read was byte-identical while the DATA was
180 cards and three days apart. ``store_uuid`` is a ROW in ``schema_meta``, and
a dump/restore into a second cluster carries rows — which is precisely how
those two came to share one. An identity that survives being copied cannot
answer "am I connected to the store I think I am".

``system_identifier`` is generated by ``initdb`` for the CLUSTER and appears in
no dump, so a restore cannot carry it. The two clusters above differ on it, and
that difference is the question this card was asking.

WHAT THESE TESTS PIN, and one thing they deliberately do not: they pin the
PROBE's contract — that a real server answers KNOWN, that the TYPE refuses the
shapes that would let a caller mistake absence for a value, and that an
UNKNOWN must carry a stated reason rather than an invented identity.

THE UNKNOWN ARM IS NOW EXERCISED THROUGH THE VALIDATOR, NOT THROUGH A SECOND
ENGINE. It used to be reached by opening a file store, which answered UNKNOWN
because it had no cluster to ask. There is one storage engine now and a
filename names no store at all, so that route is gone -- but the arm it
reached is not decoration: an ``UNKNOWN`` that carries a placeholder id makes
two unknowns compare EQUAL, which is the exact collapse this module exists to
prevent. It is pinned below against ``StoreInstance``'s own validator, which
is where the invariant actually lives.
They do NOT claim any guard consumes it yet; the guard is the next step and
owns its own tests, because having the instrument is exactly what makes the
missing guard LOOK done.
"""

from __future__ import annotations

import os

import pytest

from scitex_cards._db import connect
from scitex_cards._store_instance import (
    Certainty,
    IdentityVerdict,
    StoreInstance,
    check_store_identity,
    store_instance,
)
from scitex_cards._store_url import BACKEND_POSTGRES, BACKEND_UNSUPPORTED

#: The store this test is pinned to by the root ``conftest.py`` -- a uniquely
#: named, throwaway PostgreSQL schema, created and dropped per test.
_ENV_STORE = "SCITEX_CARDS_DB"


@pytest.fixture
def pg_conn():
    """A live connection to this test's own throwaway store. NEVER A SKIP.

    THIS FIXTURE USED TO SKIP, and that is why it is written out at length
    rather than quietly repaired. It read ``$SCITEX_CARDS_TEST_PG_DSN``, a
    variable nothing in this repository, its CI, or any fleet container sets,
    and skipped when it was absent -- which was always. Every server-side
    assertion in this module therefore reported green without opening a
    connection, for as long as the variable has existed.

    That is the same failure the module docstring describes from the other
    side: an identity check that cannot fail tells you nothing, and a storage
    test that skips is indistinguishable from one that passes in a summary
    line. So the target is now the store the harness already guarantees, and
    its absence is a FAILURE naming what is missing.
    """
    dsn = os.environ.get(_ENV_STORE, "")
    if "search_path" not in dsn:
        pytest.fail(
            f"the root conftest did not pin ${_ENV_STORE} to a throwaway "
            f"PostgreSQL schema; it holds {dsn!r}. This is a failure and not a "
            "skip: a skipped identity test and a passing one look identical, "
            "which is how this module went unexercised.",
            pytrace=False,
        )
    conn = connect(dsn)
    try:
        yield conn
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# The probe
# ---------------------------------------------------------------------------
def test_a_postgres_connection_knows_its_instance(pg_conn):
    """A real server answers KNOWN — the probe is not merely well-typed."""
    # Arrange
    conn = pg_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.certainty is Certainty.KNOWN


def test_a_postgres_instance_id_is_the_clusters_own_identifier(pg_conn):
    """The value is the cluster's, read from the server, not synthesised.

    Reads the control row through ``_sole_value`` rather than ``row[0]``. The
    first draft of this test used the index and raised ``KeyError: 0`` against
    a real server — psycopg's ``dict_row`` yields a real dict, which accepts
    only the NAME. That is the fourth instance of the bug ``_sole_value``'s own
    docstring calls "a pattern rather than three accidents", found by writing a
    test for something else, which is the argument for the helper existing.
    """
    # Arrange
    from scitex_cards._schema_probe import _sole_value

    expected = str(
        _sole_value(
            pg_conn.execute(
                "select system_identifier::text from pg_control_system()"
            ).fetchone()
        )
    )
    # Act
    instance = store_instance(pg_conn)
    # Assert
    assert instance.instance_id == expected


def test_a_known_answer_carries_a_reason_of_none(pg_conn):
    """A reason explains an UNKNOWN; carrying one on a KNOWN is a contradiction.

    Replaces three tests that reached the UNKNOWN arm by opening a FILE store.
    That route is gone -- a filename names no store now -- and the arm itself
    is pinned against the validator further down, which is where the invariant
    lives rather than where one particular engine happened to trigger it.
    """
    # Arrange
    conn = pg_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.reason is None


def test_the_backend_comes_from_the_live_connection(pg_conn):
    """Read from what is actually open, never from a caller's belief.

    Being wrong about the backend on this module means answering a question
    about the wrong instance.
    """
    # Arrange
    conn = pg_conn
    # Act
    instance = store_instance(conn)
    # Assert
    assert instance.backend == BACKEND_POSTGRES


# ---------------------------------------------------------------------------
# The type refuses the shapes that would let absence pass for a value.
#
# These run the VALIDATOR, which is the only thing standing between a caller
# and a comparison that cannot fail. Each varies ONE condition: nothing else
# about the construction is wrong, so a test passing here cannot be passing
# for another reason. (A guard exercised only through cases that also fail for
# a second reason is untested — scitex-db measured exactly that on their own
# preflight guard the same night this was written: they deleted it and 21
# tests stayed green.)
# ---------------------------------------------------------------------------
def _refusal_message(**kwargs) -> str:
    """The text the validator refuses ``kwargs`` with.

    Mirrors ``test__store_verify._verify_error_message``: the raise is the
    expectation here, so a test built on this helper spends its one assertion
    on WHICH refusal it got — a bare ``pytest.raises(ValueError)`` would pass
    on any of the four and prove none of them.
    """
    with pytest.raises(ValueError) as excinfo:
        StoreInstance(**kwargs)
    return str(excinfo.value)


def test_a_known_identity_must_carry_the_value_it_claims_to_know():
    """KNOWN with no id is a claim with nothing behind it."""
    # Arrange
    claimed = {"backend": BACKEND_POSTGRES, "certainty": Certainty.KNOWN}
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "must carry the value" in message


def test_an_unknown_identity_must_not_carry_a_value():
    """Otherwise two UNKNOWNs compare EQUAL on a shared placeholder.

    That is the collapse this module exists to prevent, reintroduced at the
    type level — the most expensive place to hide it, because every caller
    would then be correct by inspection and wrong in fact.
    """
    # Arrange — a stated reason, so ONLY the id is wrong here
    claimed = {
        "backend": BACKEND_UNSUPPORTED,
        "certainty": Certainty.UNKNOWN,
        "instance_id": "placeholder",
        "reason": "this target names no store: cannot tell",
    }
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "two unknowns can never compare equal" in message


def test_an_unknown_identity_must_say_why():
    """A caller cannot tell a missing capability from a broken connection."""
    # Arrange
    claimed = {"backend": BACKEND_UNSUPPORTED, "certainty": Certainty.UNKNOWN}
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "must say why" in message


def test_a_known_identity_carries_no_reason():
    """A reason explains an UNKNOWN; on a KNOWN it is a contradiction."""
    # Arrange
    claimed = {
        "backend": BACKEND_POSTGRES,
        "certainty": Certainty.KNOWN,
        "instance_id": "7668165447904178049",
        "reason": "this should not be here",
    }
    # Act
    message = _refusal_message(**claimed)
    # Assert
    assert "reason explains an UNKNOWN" in message


# ---------------------------------------------------------------------------
# The guard. Only MATCHES proceeds.
#
# THE ISOLATING CASE is `test_a_pinned_identity_that_differs_refuses`: expected
# is SET, certainty is KNOWN, the connection is live and the schema current —
# everything valid, ONE condition varying. Delete the mismatch branch and that
# test goes red while every other test here stays green, which is what makes it
# a gate rather than a formality.
#
# It is written that way on purpose. A guard exercised only through cases that
# ALSO fail for a second reason is untested — scitex-db measured exactly that
# on their own preflight guard the night this was written: they deleted it and
# 21 tests stayed green, because every case asserting failure also carried a
# failing finding.
# ---------------------------------------------------------------------------
def test_a_pinned_identity_that_matches_proceeds(pg_conn):
    """The positive control: without it, a guard that refuses everything passes.

    BOTH HALVES ARE PINNED HERE, and that is a DELIBERATE CHANGE made
    2026-08-19 rather than a repair to a broken test. Until then this passed
    the instance alone and expected ``may_proceed is True``; it now supplies a
    uuid pair as well, because an instance-only pin answers ``CANNOT_TELL``
    under the corrected contract.

    WHY THE CONTRACT CHANGED: the instance identifies the SERVER. A database
    frozen and restored onto that same server keeps its ``system_identifier``
    and gets a NEW ``store_uuid``, so an instance-only pin passes exactly the
    2026-08-09 frozen-store incident the pin exists to catch. See
    ``_store_identity_decision.decide_identity`` for all nine rows and
    ``test__identity_decision_both_halves.py`` for the per-half mutation table.

    THE PURPOSE OF THIS TEST IS UNCHANGED and is why it was updated rather than
    deleted: it is the one case asserting a PASS, so it is what stops a guard
    that refuses everything from looking correct.
    """
    # Arrange
    pinned = store_instance(pg_conn).instance_id
    pinned_uuid = "1d55dd6e-3d2a-4c24-a429-a78835ab988f"
    # Act
    check = check_store_identity(
        pg_conn,
        pinned,
        observed_uuid=pinned_uuid,
        expected_uuid=pinned_uuid,
    )
    # Assert
    assert check.may_proceed is True


def test_a_pinned_identity_that_differs_refuses(pg_conn):
    """ISOLATING: everything valid, only the VALUE differs.

    The wrong value here stands in for the measured case — two live clusters
    carrying store_uuid 1d55dd6e-…-a78835ab988f with 180 cards and three days
    between them. One cluster is enough to pin the behaviour; the second is
    what proved it was needed.
    """
    # Arrange
    not_this_cluster = "7671108644284358700"
    # Act
    check = check_store_identity(pg_conn, not_this_cluster)
    # Assert
    assert check.verdict is IdentityVerdict.DIFFERS


def test_a_differing_identity_names_both_sides(pg_conn):
    """A refusal a reader cannot check is a refusal they must take on faith."""
    # Arrange
    not_this_cluster = "7671108644284358700"
    # Act
    check = check_store_identity(pg_conn, not_this_cluster)
    # Assert
    assert not_this_cluster in (check.reason or "")


def test_nothing_pinned_cannot_tell(pg_conn):
    """An unpinned client is the one that reads a stale replica confidently."""
    # Arrange
    conn = pg_conn
    # Act
    check = check_store_identity(conn, None)
    # Assert
    assert check.verdict is IdentityVerdict.CANNOT_TELL


def test_nothing_pinned_does_not_proceed(pg_conn):
    """CANNOT_TELL refuses. Collapsing it into a pass is the defect itself.

    Separate from the verdict assertion above because the verdict and the
    PERMISSION are different claims: a later refactor could keep the verdict
    correct and let `may_proceed` fall through.
    """
    # Arrange
    conn = pg_conn
    # Act
    check = check_store_identity(conn, None)
    # Assert
    assert check.may_proceed is False


def test_the_two_refusals_do_not_share_a_message(pg_conn):
    """"Wrong store" and "cannot tell which store" need different actions.

    The reason string is the only part a human acts on, so the two refusals
    staying distinguishable is the feature, not the wording.

    THE SECOND REFUSAL CHANGED IDENTITY, deliberately. It used to be "the store
    cannot report an identity at all", reached by opening a file store, and a
    companion test asserted that case refuses. Neither survives: the one engine
    that remains always answers ``pg_control_system()``, so a store that cannot
    report an identity is not a state this package can be in. The pair compared
    here is now the two refusals that DO exist -- nothing pinned, and a pin that
    does not match -- which is the distinction a human actually acts on.
    """
    # Arrange
    conn = pg_conn
    # Act
    unpinned = check_store_identity(conn, None).reason
    mismatched = check_store_identity(conn, "7668165447904178049").reason
    # Assert
    assert unpinned != mismatched


# EOF
