#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Standalone user registry for scitex-todo — board MEMBERSHIP SSOT.

scitex-todo is the single source of truth for who may be an assignee,
collaborator, or subscriber on the board — HUMANS and AGENTS alike. Until
now a "user" was just a mutable name string in each card's ``agent`` /
``assignee`` field, so renaming an owner (e.g. ``proj-scitex-dev`` →
``scitex-dev``) silently broke every reference. This package adds a
STANDALONE user registry with STABLE, never-reused ids: a card owner string
resolves to a :class:`User` whose ``id`` is the durable handle, while the
mutable display names live in the user's ``names`` alias list.

Storage
-------
Users persist in the SAME YAML store file as tasks, under a top-level
``users:`` key (a sibling of ``tasks:``). The write path reuses the task
store's :func:`scitex_cards._model._store_lock` advisory lock and a ruamel
round-trip writer so the hand-written ``tasks:`` payload, its inline
comments, and key order survive every user-side write untouched (and vice
versa). There is NO separate users file.

Hard standalone constraint
---------------------------
This package has ZERO dependency on any external agent runtime or fleet
package, in either direction, and works with no external runtime present. It
reuses :func:`scitex_cards._ports.canonical_agent_id` purely as a local
string normaliser/validator for the optional ``host_at_name`` join key —
it does NOT import ``AgentDirectoryPort`` or perform any liveness pull. The
eventual identity bridge (mapping a user to a live ``host@name`` agent
runtime) is a BUS-ONLY, separate follow-up and is intentionally NOT built
here.

Id format
---------
A user id is the literal prefix ``u_`` followed by 12 lowercase hex
characters: ``u_3f9a1c0b7e42``. Ids are GENERATED by :func:`register_user`
(random via :func:`secrets.token_hex`, 48 bits of entropy) — or SUPPLIED by
the caller in the same validated format, e.g. the deterministic OIDC-derived
id from :func:`deterministic_user_id`, so the same human converges to the
same id on every host (card
``cards-email-uniqueness-is-fleet-wide-not-per-host-20260814``, 2026-08-14).
Ids are STABLE for the life of the user and are NEVER reused even after a
user is removed.

Layout: :mod:`._model` holds the schema + validation; :mod:`._store` holds
the persistence + registry functions. This module re-exports the public
surface so ``from scitex_cards._users import register_user`` keeps working.
"""

from __future__ import annotations

from ._identity import (
    ENV_STRICT_IDENTITY,
    IDENTITY_ALIASES,
    IDENTITY_PREFIXES,
    KNOWN_HOSTS,
    UnknownIdentityError,
    canonical_identity,
    resolve_identity,
    strict_identity_enabled,
)
from ._model import (
    DEFAULT_LIVENESS_TTL_SECONDS,
    VALID_USER_KINDS,
    User,
    UserValidationError,
    is_alive,
    user_turn_url,
    validate_user,
)
from ._store import (
    add_alias,
    deterministic_user_id,
    get_user,
    list_users,
    load_users,
    register_user,
    resolve_user,
    set_notify,
    touch_user,
)

__all__ = [
    "DEFAULT_LIVENESS_TTL_SECONDS",
    "ENV_STRICT_IDENTITY",
    "IDENTITY_ALIASES",
    "IDENTITY_PREFIXES",
    "KNOWN_HOSTS",
    "VALID_USER_KINDS",
    "UnknownIdentityError",
    "User",
    "UserValidationError",
    "add_alias",
    "canonical_identity",
    "deterministic_user_id",
    "get_user",
    "is_alive",
    "list_users",
    "load_users",
    "register_user",
    "resolve_identity",
    "resolve_user",
    "set_notify",
    "strict_identity_enabled",
    "touch_user",
    "user_turn_url",
    "validate_user",
]

# EOF
